baseurl = "https://adoring-keller-b92581.netlify.com/"
DefaultContentLanguage = "en"
title = "Data Finance Tech Solutions"
theme = "beautifulhugo"

[Params]
  subtitle = "Some useful insights around data science, finance, and credit solutions, all of this used in a strategic way"
  dateFormat = "January 2, 2006"

[Author]
  name = "Prof. Andre Salerno, MSc"
  #website = "https://www.vincent-lunot.com"
  email = "andresalerno22@gmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
